# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='shortcode',
            field=models.CharField(default='defaultshortcode', max_length=20),
            preserve_default=False,
        ),
    ]
